### ISSUE TITLE
meadowphysics v2 doesn't work on non-varibright grids

### ISSUE THREAD

**Issue by nightmorph** [monome/meadowphysics-maxpat#2]
the newest meadowphysics, even with the re-added mp-note patch, doesn't display anything on my grayscale128.

max runtime 5, osx 10.8.5.

the max log window is filled up with these messages:

```
bpatcher: bpatcher: error loading patcher channel_plug.maxpat
js: mp.js: Javascript TypeError: redeclaration of const max, line 40
binding to port 17812
bpatcher: jpatchline_new: index out of range
jpatchline_plugin: box missing outlet number 2
bpatcher: jpatchline_new: index out of range
jpatchline_plugin: box missing outlet number 1
jpatchline_completeconnection: index out of range.
binding to port 15598
serialosc.maxpat: 2013-may-20 
js: no function redraw
js: no function next
js: no function redraw
js: no function next
<infinite repeats of the above function errors>
```

**Comment by tehn** [comment]
it'll be a minute before i can implement non-varbright into the js. this
should really be handled by the serialosc daemon, so that's also on my list.

note that this new MP requires max 7 hence the error messages.

**Comment by nightmorph** [comment]
yeah, i saw the runtime requirement in the lines thread just after i filed the bug. updating to max7 removes the error messages. once connected to a softsynth, i can even interact with MP on the grid, though of course without any visual feedback from the LEDs. looking forward to the monobright update; thanks.

**Comment by nightmorph** [comment]
the latest version displays properly on my gs128. thank you very much for the update.

some visual usability ideas for monobright grids:

- when a note range/row is displayed, the start point of each trigger could briefly rapidly flash as it starts moving, to indicate the trigger's current position.
- same thing for the indicators when the leftmost key is held; the parameter columns would indicate any changes from the default by rapidly flashing the appropriate button.

* * *

finally, i think this latest update introduced some midi bugs when using an external synth. quite often i get hanging notes when changing notes in the scale box. hanging notes cannot be altered by pressing the appropriate row stop keys, toggling the MP "on" button, nor by changing length on each trig row. the only solution is to either power cycle my juno106, or kill and restart meadowphysics.

**Comment by nightmorph** [comment]
the original bug was fixed a long time ago; mp2 works on non-varibright grids. (i also no longer have any way of testing further, as i don't have the gs128 anymore.)
